# Generated by Django 5.1.2 on 2024-10-26 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCheckReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_guid", models.CharField(db_index=True, max_length=255)),
                ("installation_id", models.BigIntegerField()),
                ("subdomain", models.CharField(max_length=255)),
                ("plan", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("version", models.CharField(max_length=50)),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance_guid", "created_at"],
                        name="healthcheck_instanc_7b6a5b_idx",
                    )
                ],
            },
        ),
    ]
