# Generated by Django 5.1.2 on 2025-01-05 20:16

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCheckMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("instance_guid", models.CharField(max_length=320)),
                ("subdomain", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "notification_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            max_length=254,
                            validators=[django.core.validators.EmailValidator()],
                        ),
                        blank=True,
                        help_text="List of email addresses to receive reports",
                        size=None,
                    ),
                ),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                ("next_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["installation_id"],
                        name="healthcheck_install_26f1a6_idx",
                    ),
                    models.Index(
                        fields=["next_check"], name="healthcheck_next_ch_3a209a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthCheckReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_guid", models.CharField(db_index=True, max_length=320)),
                ("installation_id", models.BigIntegerField()),
                ("app_guid", models.CharField(max_length=320)),
                ("subdomain", models.CharField(max_length=255)),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        help_text="Admin email for API authentication",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        blank=True,
                        help_text="API token for authentication",
                        max_length=550,
                        null=True,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
                ("version", models.CharField(max_length=50)),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_unlocked", models.BooleanField(default=False)),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance_guid", "created_at"],
                        name="healthcheck_instanc_7b6a5b_idx",
                    ),
                    models.Index(
                        fields=["installation_id", "created_at"],
                        name="healthcheck_install_c0ea02_idx",
                    ),
                    models.Index(
                        fields=["subdomain", "created_at"],
                        name="healthcheck_subdoma_f62e37_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ZendeskUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=100)),
                ("locale", models.CharField(max_length=50)),
                ("time_zone", models.CharField(blank=True, max_length=100, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("subdomain", models.CharField(max_length=255)),
                ("plan", models.CharField(blank=True, max_length=320, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="healthcheck_user_id_750586_idx"
                    ),
                    models.Index(fields=["email"], name="healthcheck_email_f4e07f_idx"),
                ],
            },
        ),
    ]
