# Generated by Django 5.1.4 on 2025-02-21 03:24

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_widget_script",
                    models.TextField(
                        blank=True,
                        help_text="Paste the complete chat widget script here. It will be embedded in the base template.",
                    ),
                ),
                (
                    "is_chat_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Toggle to enable/disable the chat widget across the site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.AlterField(
            model_name="healthcheckmonitoring",
            name="notification_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(
                    max_length=254, validators=[django.core.validators.EmailValidator()]
                ),
                blank=True,
                default=list,
                help_text="List of email addresses to receive reports",
                null=True,
                size=None,
            ),
        ),
    ]
