# Generated by Django 5.1.4 on 2025-01-05 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0002_cleanup_webhook_endpoints"),
    ]

    operations = []
