# Generated by Django 5.1.2 on 2024-10-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0004_reportunlock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportunlock",
            name="report",
        ),
        migrations.AddField(
            model_name="healthcheckreport",
            name="is_unlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthcheckreport",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddIndex(
            model_name="healthcheckreport",
            index=models.Index(
                fields=["installation_id", "created_at"],
                name="healthcheck_install_c0ea02_idx",
            ),
        ),
        migrations.DeleteModel(
            name="ReportUnlock",
        ),
    ]
