# Generated by Django 5.1.2 on 2024-10-29 01:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0005_remove_reportunlock_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("instance_guid", models.CharField(max_length=320)),
                ("subdomain", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "notification_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            max_length=254,
                            validators=[django.core.validators.EmailValidator()],
                        ),
                        blank=True,
                        help_text="List of email addresses to receive reports",
                        size=None,
                    ),
                ),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                ("next_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["installation_id"],
                        name="healthcheck_install_26f1a6_idx",
                    ),
                    models.Index(
                        fields=["next_check"], name="healthcheck_next_ch_3a209a_idx"
                    ),
                ],
            },
        ),
    ]
