# Generated by Django 5.1.2 on 2024-11-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0006_healthcheckmonitoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheckreport",
            name="admin_email",
            field=models.EmailField(
                blank=True,
                help_text="Admin email for API authentication",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcheckreport",
            name="api_token",
            field=models.CharField(
                blank=True,
                help_text="API token for authentication",
                max_length=550,
                null=True,
            ),
        ),
    ]
