# Generated by Django 5.1.2 on 2024-11-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0007_healthcheckreport_admin_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZendeskUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=100)),
                ("locale", models.CharField(max_length=50)),
                ("time_zone", models.CharField(blank=True, max_length=100, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("subdomain", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="healthcheck_user_id_750586_idx"
                    ),
                    models.Index(fields=["email"], name="healthcheck_email_f4e07f_idx"),
                ],
            },
        ),
    ]
