# Generated by Django 5.1.2 on 2024-12-19 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0012_2_8"),
        ("healthcheck", "0009_zendeskuser_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djstripe.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djstripe.subscription",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["installation_id"],
                        name="healthcheck_install_04c1bd_idx",
                    )
                ],
            },
        ),
    ]
