# Generated by Django 5.1.2 on 2024-12-21 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0010_healthchecksubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HealthCheckSubscription",
        ),
    ]
