# Generated by Django 5.1.2 on 2024-12-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0011_delete_healthchecksubscription"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="healthcheckreport",
            index=models.Index(
                fields=["subdomain", "created_at"],
                name="healthcheck_subdoma_f62e37_idx",
            ),
        ),
    ]
